//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNSABC.Web.DNSABC_Dns {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblProductID;
	protected global::System.Web.UI.WebControls.Label lblUserID;
	protected global::System.Web.UI.WebControls.Label lblDomain;
	protected global::System.Web.UI.WebControls.Label lblPASSWORD;
	protected global::System.Web.UI.WebControls.Label lblStartTime;
	protected global::System.Web.UI.WebControls.Label lblEndTime;
	protected global::System.Web.UI.WebControls.Label lblisHost;
	protected global::System.Web.UI.WebControls.Label lblisTtl;
	protected global::System.Web.UI.WebControls.Label lblisMonitor;
	protected global::System.Web.UI.WebControls.Label lblisGroupID;
	protected global::System.Web.UI.WebControls.Label lblState;
	protected global::System.Web.UI.WebControls.Label lblRemark;
	protected global::System.Web.UI.WebControls.Label lblUpdateTime;
	protected global::System.Web.UI.WebControls.Label lblCreateTime;


       
    }
}
