//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3603
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROYcms.Blog.Web.App_Blog {
    
    
    public partial class index {
        
        /// <summary>
        /// __inc1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.UserControl @__inc1;
        
        /// <summary>
        /// __Css1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ROYcms.Blog.Web.App_Blog.Css @__Css1;
        
        /// <summary>
        /// Myform 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm Myform;
        
        /// <summary>
        /// __Top1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ROYcms.Blog.Web.@__Top @__Top1;
        
        /// <summary>
        /// __header1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ROYcms.Blog.Web.App_Blog.@__header @__header1;
        
        /// <summary>
        /// __Ucenter2 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ROYcms.Blog.Web.App_Blog.@__Ucenter @__Ucenter2;
        
        /// <summary>
        /// __calendar1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ROYcms.Blog.Web.App_Blog.@__calendar @__calendar1;
        
        /// <summary>
        /// __flash1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ROYcms.Blog.Web.App_Blog.@__flash @__flash1;
        
        /// <summary>
        /// __search1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ROYcms.Blog.Web.App_Blog.@__search @__search1;
        
        /// <summary>
        /// __pagelink1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ROYcms.Blog.Web.App_Blog.@__pagelink @__pagelink1;
        
        /// <summary>
        /// __Tag1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ROYcms.Blog.Web.App_Blog.@__Tag @__Tag1;
        
        /// <summary>
        /// __comment1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ROYcms.Blog.Web.App_Blog.@__comment @__comment1;
        
        /// <summary>
        /// Repeater_list 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater Repeater_list;
        
        /// <summary>
        /// __Related1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ROYcms.Blog.Web.App_Blog.@__Related @__Related1;
        
        /// <summary>
        /// __footer1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ROYcms.Blog.Web.App_Blog.@__footer @__footer1;
        
        /// <summary>
        /// __end1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::ROYcms.Blog.Web.App_Blog.End @__end1;
    }
}
