//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNSABC.Web.DNSABC_ProductInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblProductType;
	protected global::System.Web.UI.WebControls.Label lblProductName;
	protected global::System.Web.UI.WebControls.Label lblProductPic;
	protected global::System.Web.UI.WebControls.Label lblProductDescription;
	protected global::System.Web.UI.WebControls.Label lblProductTableName;
	protected global::System.Web.UI.WebControls.Label lblMONTH;
	protected global::System.Web.UI.WebControls.Label lblState;
	protected global::System.Web.UI.WebControls.Label lblisOrder;
	protected global::System.Web.UI.WebControls.Label lblRemark;
	protected global::System.Web.UI.WebControls.Label lblUpdateTime;
	protected global::System.Web.UI.WebControls.Label lblCreateTime;


       
    }
}
