/*
* DD_belatedPNG: Adds IE6 support: PNG images for CSS background-image and HTML <IMG/>.
* Author: Drew Diller
* Email: drew.diller@gmail.com
* URL: http://www.dillerdesign.com/experiment/DD_belatedPNG/
* Version: 0.0.8a
* Licensed under the MIT License: http://dillerdesign.com/experiment/DD_belatedPNG/#license
*
* Example usage:
* DD_belatedPNG.fix('.png_bg'); // argument is a CSS selector
* DD_belatedPNG.fixPng( someNode ); // argument is an HTMLDomElement
*/
var DD_belatedPNG={ns:"DD_belatedPNG",imgSize:{},delay:10,nodesFixed:0,createVmlNameSpace:function(){if(document.namespaces&&!document.namespaces[this.ns]){document.namespaces.add(this.ns,"urn:schemas-microsoft-com:vml")
}},createVmlStyleSheet:function(){var B,A;B=document.createElement("style");B.setAttribute("media","screen");document.documentElement.firstChild.insertBefore(B,document.documentElement.firstChild.firstChild);if(B.styleSheet){B=B.styleSheet;B.addRule(this.ns+"\\:*","{behavior:url(#default#VML)}");B.addRule(this.ns+"\\:shape","position:absolute;");B.addRule("img."+this.ns+"_sizeFinder","behavior:none; border:none; position:absolute; z-index:-1; top:-10000px; visibility:hidden;");this.screenStyleSheet=B;
A=document.createElement("style");A.setAttribute("media","print");document.documentElement.firstChild.insertBefore(A,document.documentElement.firstChild.firstChild);A=A.styleSheet;A.addRule(this.ns+"\\:*","{display: none !important;}");A.addRule("img."+this.ns+"_sizeFinder","{display: none !important;}")}},readPropertyChange:function(){var B,C,A;B=event.srcElement;if(!B.vmlInitiated){return }if(event.propertyName.search("background")!=-1||event.propertyName.search("border")!=-1){DD_belatedPNG.applyVML(B)
}if(event.propertyName=="style.display"){C=(B.currentStyle.display=="none")?"none":"block";for(A in B.vml){if(B.vml.hasOwnProperty(A)){B.vml[A].shape.style.display=C}}}if(event.propertyName.search("filter")!=-1){DD_belatedPNG.vmlOpacity(B)}},vmlOpacity:function(B){if(B.currentStyle.filter.search("lpha")!=-1){var A=B.currentStyle.filter;A=parseInt(A.substring(A.lastIndexOf("=")+1,A.lastIndexOf(")")),10)/100;B.vml.color.shape.style.filter=B.currentStyle.filter;B.vml.image.fill.opacity=A}},handlePseudoHover:function(A){setTimeout(function(){DD_belatedPNG.applyVML(A)
},1)},fix:function(A){if(this.screenStyleSheet){var C,B;C=A.split(",");for(B=0;B<C.length;B++){this.screenStyleSheet.addRule(C[B],"behavior:expression(DD_belatedPNG.fixPng(this))")}}},applyVML:function(A){A.runtimeStyle.cssText="";this.vmlFill(A);this.vmlOffsets(A);this.vmlOpacity(A);if(A.isImg){this.copyImageBorders(A)}},attachHandlers:function(G){var C,B,F,D,A,E;C=this;B={resize:"vmlOffsets",move:"vmlOffsets"};if(G.nodeName=="A"){D={mouseleave:"handlePseudoHover",mouseenter:"handlePseudoHover",focus:"handlePseudoHover",blur:"handlePseudoHover"};
for(A in D){if(D.hasOwnProperty(A)){B[A]=D[A]}}}for(E in B){if(B.hasOwnProperty(E)){F=function(){C[B[E]](G)};G.attachEvent("on"+E,F)}}G.attachEvent("onpropertychange",this.readPropertyChange)},giveLayout:function(A){A.style.zoom=1;if(A.currentStyle.position=="static"){A.style.position="relative"}},copyImageBorders:function(B){var C,A;C={borderStyle:true,borderWidth:true,borderColor:true};for(A in C){if(C.hasOwnProperty(A)){B.vml.color.shape.style[A]=B.currentStyle[A]}}},vmlFill:function(E){if(!E.currentStyle){return 
}else{var D,F,G,B,A,C;D=E.currentStyle}for(B in E.vml){if(E.vml.hasOwnProperty(B)){E.vml[B].shape.style.zIndex=D.zIndex}}E.runtimeStyle.backgroundColor="";E.runtimeStyle.backgroundImage="";F=true;if(D.backgroundImage!="none"||E.isImg){if(!E.isImg){E.vmlBg=D.backgroundImage;E.vmlBg=E.vmlBg.substr(5,E.vmlBg.lastIndexOf('")')-5)}else{E.vmlBg=E.src}G=this;if(!G.imgSize[E.vmlBg]){A=document.createElement("img");G.imgSize[E.vmlBg]=A;A.className=G.ns+"_sizeFinder";A.runtimeStyle.cssText="behavior:none; position:absolute; left:-10000px; top:-10000px; border:none; margin:0; padding:0;";
C=function(){this.width=this.offsetWidth;this.height=this.offsetHeight;G.vmlOffsets(E)};A.attachEvent("onload",C);A.src=E.vmlBg;A.removeAttribute("width");A.removeAttribute("height");document.body.insertBefore(A,document.body.firstChild)}E.vml.image.fill.src=E.vmlBg;F=false}E.vml.image.fill.on=!F;E.vml.image.fill.color="none";E.vml.color.shape.style.backgroundColor=D.backgroundColor;E.runtimeStyle.backgroundImage="none";E.runtimeStyle.backgroundColor="transparent"},vmlOffsets:function(B){var F,L,A,C,E,K,D,J,H,G,I;
F=B.currentStyle;L={W:B.clientWidth+1,H:B.clientHeight+1,w:this.imgSize[B.vmlBg].width,h:this.imgSize[B.vmlBg].height,L:B.offsetLeft,T:B.offsetTop,bLW:B.clientLeft,bTW:B.clientTop};A=(L.L+L.bLW==1)?1:0;C=function(M,O,P,N,Q,R){M.coordsize=N+","+Q;M.coordorigin=R+","+R;M.path="m0,0l"+N+",0l"+N+","+Q+"l0,"+Q+" xe";M.style.width=N+"px";M.style.height=Q+"px";M.style.left=O+"px";M.style.top=P+"px"};C(B.vml.color.shape,(L.L+(B.isImg?0:L.bLW)),(L.T+(B.isImg?0:L.bTW)),(L.W-1),(L.H-1),0);C(B.vml.image.shape,(L.L+L.bLW),(L.T+L.bTW),(L.W),(L.H),1);
E={X:0,Y:0};if(B.isImg){E.X=parseInt(F.paddingLeft,10)+1;E.Y=parseInt(F.paddingTop,10)+1}else{for(H in E){if(E.hasOwnProperty(H)){this.figurePercentage(E,L,H,F["backgroundPosition"+H])}}}B.vml.image.fill.position=(E.X/L.W)+","+(E.Y/L.H);K=F.backgroundRepeat;D={T:1,R:L.W+A,B:L.H,L:1+A};J={X:{b1:"L",b2:"R",d:"W"},Y:{b1:"T",b2:"B",d:"H"}};if(K!="repeat"||B.isImg){G={T:(E.Y),R:(E.X+L.w),B:(E.Y+L.h),L:(E.X)};if(K.search("repeat-")!=-1){I=K.split("repeat-")[1].toUpperCase();G[J[I].b1]=1;G[J[I].b2]=L[J[I].d]
}if(G.B>L.H){G.B=L.H}B.vml.image.shape.style.clip="rect("+G.T+"px "+(G.R+A)+"px "+G.B+"px "+(G.L+A)+"px)"}else{B.vml.image.shape.style.clip="rect("+D.T+"px "+D.R+"px "+D.B+"px "+D.L+"px)"}},figurePercentage:function(D,C,F,A){var B,E;E=true;B=(F=="X");switch(A){case"left":case"top":D[F]=0;break;case"center":D[F]=0.5;break;case"right":case"bottom":D[F]=1;break;default:if(A.search("%")!=-1){D[F]=parseInt(A,10)/100}else{E=false}}D[F]=Math.ceil(E?((C[B?"W":"H"]*D[F])-(C[B?"w":"h"]*D[F])):parseInt(A,10));
if(D[F]%2===0){D[F]++}return D[F]},fixPng:function(C){C.style.behavior="none";var F,B,E,A,D;if(C.nodeName=="BODY"||C.nodeName=="TD"||C.nodeName=="TR"){return }C.isImg=false;if(C.nodeName=="IMG"){if(C.src.toLowerCase().search(/\.png$/)!=-1){C.isImg=true;C.style.visibility="hidden"}else{return }}else{if(C.currentStyle.backgroundImage.toLowerCase().search(".png")==-1){return }}F=DD_belatedPNG;C.vml={color:{},image:{}};B={shape:{},fill:{}};for(A in C.vml){if(C.vml.hasOwnProperty(A)){for(D in B){if(B.hasOwnProperty(D)){E=F.ns+":"+D;
C.vml[A][D]=document.createElement(E)}}C.vml[A].shape.stroked=false;C.vml[A].shape.appendChild(C.vml[A].fill);C.parentNode.insertBefore(C.vml[A].shape,C)}}C.vml.image.shape.fillcolor="none";C.vml.image.fill.type="tile";C.vml.color.fill.on=false;F.attachHandlers(C);F.giveLayout(C);F.giveLayout(C.offsetParent);C.vmlInitiated=true;F.applyVML(C)}};try{document.execCommand("BackgroundImageCache",false,true)}catch(r){}DD_belatedPNG.createVmlNameSpace();DD_belatedPNG.createVmlStyleSheet();