//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNSABC.Web.ROYcms_user {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblbh;
		protected global::System.Web.UI.WebControls.TextBox txtRoleID;
		protected global::System.Web.UI.WebControls.TextBox txtUgroupID;
		protected global::System.Web.UI.WebControls.TextBox txtName;
		protected global::System.Web.UI.WebControls.TextBox txtPASSWORD;
		protected global::System.Web.UI.WebControls.TextBox txtmoney;
		protected global::System.Web.UI.WebControls.TextBox txtQq;
		protected global::System.Web.UI.WebControls.TextBox txtEmail;
		protected global::System.Web.UI.WebControls.TextBox txtAge;
		protected global::System.Web.UI.WebControls.TextBox txtsex;
		protected global::System.Web.UI.WebControls.TextBox txtPic;
		protected global::System.Web.UI.WebControls.TextBox txtQuanxian;
		protected global::System.Web.UI.WebControls.TextBox txtUsername;
		protected global::System.Web.UI.WebControls.TextBox txtGuid;
		protected global::System.Web.UI.WebControls.TextBox txtIp;
		protected global::System.Web.UI.WebControls.TextBox txtLoginTime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
