//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNSABC.Web.ROYcms_user {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblbh;
	protected global::System.Web.UI.WebControls.Label lblRoleID;
	protected global::System.Web.UI.WebControls.Label lblUgroupID;
	protected global::System.Web.UI.WebControls.Label lblName;
	protected global::System.Web.UI.WebControls.Label lblPASSWORD;
	protected global::System.Web.UI.WebControls.Label lblmoney;
	protected global::System.Web.UI.WebControls.Label lblQq;
	protected global::System.Web.UI.WebControls.Label lblEmail;
	protected global::System.Web.UI.WebControls.Label lblAge;
	protected global::System.Web.UI.WebControls.Label lblsex;
	protected global::System.Web.UI.WebControls.Label lblPic;
	protected global::System.Web.UI.WebControls.Label lblQuanxian;
	protected global::System.Web.UI.WebControls.Label lblUsername;
	protected global::System.Web.UI.WebControls.Label lblGuid;
	protected global::System.Web.UI.WebControls.Label lblIp;
	protected global::System.Web.UI.WebControls.Label lblLoginTime;


       
    }
}
