//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNSABC.Web.DNSABC_Messages {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtId;
		protected global::System.Web.UI.WebControls.TextBox txtMessagesTypeID;
		protected global::System.Web.UI.WebControls.TextBox txtUserID;
		protected global::System.Web.UI.WebControls.TextBox txtTitle;
		protected global::System.Web.UI.WebControls.TextBox txtContents;
		protected global::System.Web.UI.WebControls.TextBox txtIP;
		protected global::System.Web.UI.WebControls.TextBox txtState;
		protected global::System.Web.UI.WebControls.TextBox txtUpdateTime;
		protected global::System.Web.UI.WebControls.TextBox txtCreateTime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
