//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNSABC.Web.DNSABC_ProductModelCdn {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblProductID;
	protected global::System.Web.UI.WebControls.Label lblisHost;
	protected global::System.Web.UI.WebControls.Label lblisConnection;
	protected global::System.Web.UI.WebControls.Label lblisBandwidth;
	protected global::System.Web.UI.WebControls.Label lblRemark;


       
    }
}
