//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNSABC.Web.DNSABC_Log {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblId;
		protected global::System.Web.UI.WebControls.TextBox txtUserID;
		protected global::System.Web.UI.WebControls.TextBox txtLogType;
		protected global::System.Web.UI.WebControls.TextBox txtContent;
		protected global::System.Web.UI.WebControls.TextBox txtOperator;
		protected global::System.Web.UI.WebControls.TextBox txtIp;
		protected global::System.Web.UI.WebControls.TextBox txtAdminID;
		protected global::System.Web.UI.WebControls.TextBox txtObjectType;
		protected global::System.Web.UI.WebControls.TextBox txtObjectID;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
		protected global::System.Web.UI.WebControls.TextBox txtCreateTime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
