//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNSABC.Web.DNSABC_Log {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblUserID;
	protected global::System.Web.UI.WebControls.Label lblLogType;
	protected global::System.Web.UI.WebControls.Label lblContent;
	protected global::System.Web.UI.WebControls.Label lblOperator;
	protected global::System.Web.UI.WebControls.Label lblIp;
	protected global::System.Web.UI.WebControls.Label lblAdminID;
	protected global::System.Web.UI.WebControls.Label lblObjectType;
	protected global::System.Web.UI.WebControls.Label lblObjectID;
	protected global::System.Web.UI.WebControls.Label lblRemark;
	protected global::System.Web.UI.WebControls.Label lblCreateTime;


       
    }
}
