//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNSABC.Web.DNSABC_UserInfo {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblId;
		protected global::System.Web.UI.WebControls.TextBox txtUserId;
		protected global::System.Web.UI.WebControls.TextBox txtAccountBalance;
		protected global::System.Web.UI.WebControls.TextBox txtAvilableBalance;
		protected global::System.Web.UI.WebControls.TextBox txtConsumedAmount;
		protected global::System.Web.UI.WebControls.TextBox txtMoney;
		protected global::System.Web.UI.WebControls.TextBox txtGradeID;
		protected global::System.Web.UI.WebControls.TextBox txtState;
		protected global::System.Web.UI.WebControls.TextBox txtRealName;
		protected global::System.Web.UI.WebControls.TextBox txtQq;
		protected global::System.Web.UI.WebControls.TextBox txtMobil;
		protected global::System.Web.UI.WebControls.TextBox txtTel;
		protected global::System.Web.UI.WebControls.TextBox txtAddress;
		protected global::System.Web.UI.WebControls.TextBox txtPostcode;
		protected global::System.Web.UI.WebControls.TextBox txtWebsite;
		protected global::System.Web.UI.WebControls.TextBox txtIDcardNum;
		protected global::System.Web.UI.WebControls.TextBox txtAccountType;
		protected global::System.Web.UI.WebControls.TextBox txtSiteID;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
