//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNSABC.Web.DNSABC_UserInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblUserId;
	protected global::System.Web.UI.WebControls.Label lblAccountBalance;
	protected global::System.Web.UI.WebControls.Label lblAvilableBalance;
	protected global::System.Web.UI.WebControls.Label lblConsumedAmount;
	protected global::System.Web.UI.WebControls.Label lblMoney;
	protected global::System.Web.UI.WebControls.Label lblGradeID;
	protected global::System.Web.UI.WebControls.Label lblState;
	protected global::System.Web.UI.WebControls.Label lblRealName;
	protected global::System.Web.UI.WebControls.Label lblQq;
	protected global::System.Web.UI.WebControls.Label lblMobil;
	protected global::System.Web.UI.WebControls.Label lblTel;
	protected global::System.Web.UI.WebControls.Label lblAddress;
	protected global::System.Web.UI.WebControls.Label lblPostcode;
	protected global::System.Web.UI.WebControls.Label lblWebsite;
	protected global::System.Web.UI.WebControls.Label lblIDcardNum;
	protected global::System.Web.UI.WebControls.Label lblAccountType;
	protected global::System.Web.UI.WebControls.Label lblSiteID;


       
    }
}
